# Generated by Django 5.1.6 on 2025-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coustomer_created_at_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('barcode', 'variant', 'category')},
        ),
    ]
