# Generated by Django 5.1.6 on 2025-03-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_payment_customer_orderpayment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='customer',
        ),
    ]
