# Generated by Django 5.1.6 on 2025-03-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
