# Generated by Django 5.1.6 on 2025-03-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_note_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.PositiveIntegerField()),
                ('sold_price', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
    ]
