# Generated by Django 5.1.6 on 2025-03-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_invoice_product_order_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total_payment',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
