# Generated by Django 5.1.6 on 2025-03-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
