# Generated by Django 5.1.6 on 2025-03-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_order_sub_total_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_payment',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
