# Generated by Django 5.1.6 on 2025-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
