# Generated by Django 5.1.6 on 2025-03-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
