# Generated by Django 5.1.6 on 2025-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
