# Generated by Django 5.1.6 on 2025-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_order_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
