# Generated by Django 5.1.6 on 2025-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_cost_alter_category_name_alter_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
