# Generated by Django 5.1.6 on 2025-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_orderitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
