# Generated by Django 5.1.6 on 2025-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_orderitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cost',
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
